config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :micropost, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  respond_to :html, :js

  def create
    @micropost = Micropost.find(params[:micropost_id])
    @like = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
    @likes = Like.where(micropost_id: params[:micropost_id])

    redirect_to root_url
    # respond_with root_url
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id]).destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
    redirect_to root_url
    # respond_with root_url
  end

end

app/views/likes/_like.html.erb
<div id="like-buttons_<%= micropost.id %>">
  <% if micropost.like_by?(current_user) %>
  <%= button_to micropost_like_path(likes, micropost_id: micropost.id), method: :delete,  remote: true do %>
  <%= image_tag("icon_red_heart.png") %>
  <span id="create">
    <%= micropost.likes_count %>
  </span>
  <% end %>

  <% else %>
  <%= button_to micropost_likes_path(micropost), remote: true do %>
  <%= image_tag("icon_heart.png") %>
  <span id="destroy">
    <%= micropost.likes_count %>
  </span>
  <% end %>
  <% end %>
</div>

app/views/likes/create.js.erb
$("#like-buttons_#{@micropost.id}").html("<%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes, like: @like}) %>")

app/views/likes/destroy.js.erb
$("#like-buttons_#{@micropost.id}").html("<%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes}) %>")